use cb;

select * from customer_behavior;


-- the total revenue generated by male vs. female customers
select gender , sum(purchase_amount) as revenue
from customer_behavior
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id,  purchase_amount
from customer_behavior
where discount_applied='Yes' 
and purchase_amount > ( select avg(purchase_amount)
						from customer_behavior)

-- Which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating),2) as ' Average Product Rating'
from customer_behavior
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, 
round(AVG(purchase_amount),2)  
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

/* Do subscribed customers spend more? 
Compare average spend and total revenue between subscribers and non-subscribers*/
select subscription_status
,count(customer_id) as 'Total Customer'  
,round(avg(purchase_amount),2) as 'Average Purchase Amount'  
,round(sum(purchase_amount),2) as 'Total Purchase Amount'
from customer_behavior
group by subscription_status 
order by 'Total Purchase Amount' ,'Average Purchase Amount' desc;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased 
,round(sum( case when discount_applied='Yes' then 1 else 0 end) * 100 / count(*),2) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;


/* Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
and show the count of each segment.*/
with customer_type as (
select 
case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment 
from customer_behavior
    )
select customer_segment , count(*) as 'Number of Customer'
from customer_type
group by customer_segment;

-- What are the top 3 most purchased products within each category? 
with item_count as (
select 
category
,item_purchased
, count(customer_id) as total_orders
, row_number() over ( partition by category order by count(customer_id) desc)  as item_rank
from customer_behavior
group by category, item_purchased
)
select 
item_rank
,category
,item_purchased
,total_orders
from item_count
where item_rank<=3;

/*Are customers 
who are repeat buyers (more than 5 previous purchases) also likely to subscribe?*/
select 
 subscription_status
,count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases>5 
group by subscription_status

-- What is the revenue contribution of each age group? 
select
age_group
,sum(purchase_amount) as revenue
from customer_behavior
group by age_group
order by revenue desc;
